name: ServerOneDiscordbot
version: 0.1
discription: Connects features between Minecraft and Discord
main: de.serverone.discordbot.ServerOneDiscordBot
authors: [Robotix_00, Luigistar]
depend:
- ServerOneSource
softdepend:
- PermissionsOne
commands:
   helpop:
      usage: /helpop [message]
      description: Sendet eine Nachricht an den Support
   unlock:
      usage: /unlock [key]
      description: Schaltet den Spieler frei